# 1. Create a 3x3x3 array with random values 

In [32]:
import numpy as np
A = np.random.random((3,3,3))
print(A)

[[[0.5973041  0.66358865 0.04168166]
  [0.23461563 0.40629358 0.92068675]
  [0.12596195 0.85784801 0.44408542]]

 [[0.81888537 0.63297079 0.0071764 ]
  [0.19157641 0.15492007 0.07710485]
  [0.80019503 0.30314259 0.38375815]]

 [[0.54502077 0.0545778  0.46755302]
  [0.04875045 0.36729684 0.96426053]
  [0.81118348 0.14783742 0.25702518]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [36]:
import numpy as np
A = np.diag([1, 2, 3, 4])
print(A)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [37]:
import numpy as np
A = np.ones((3,3))
A = np.zeros((8,8),dtype=int)
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [38]:
import numpy as np
A= np.random.random((3,3))
print("Original Array:")
print(A)
xmax, xmin = A.max(), A.min()
A = (A - xmin)/(xmax - xmin)
print("After normalization:")
print(A)

Original Array:
[[0.74226807 0.89648103 0.27808906]
 [0.52575435 0.76252475 0.20028284]
 [0.42763161 0.13042666 0.76616958]]
After normalization:
[[0.79869189 1.         0.19275707]
 [0.51605695 0.82513476 0.09118957]
 [0.38796848 0.         0.82989269]]


# 5.  How to find common values between two arrays?

In [5]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [7]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 0 0 1 1 0]
Second array:
[0 0 0 1 0 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.33324859 0.79189197 0.49166725 0.95646959 0.47611317 0.8032014
 0.73808832 0.04619673 0.73524446 0.06811733]
Maximum value replaced by 0:
[0.33324859 0.79189197 0.49166725 0.         0.47611317 0.8032014
 0.73808832 0.04619673 0.73524446 0.06811733]


# 9. How to print all the values of an array?

In [11]:
import numpy as np
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [12]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.33333084 0.56537816 0.47296493 0.88011168 0.05014945 0.50975429
  0.44842809 0.04525576 0.10274592 0.79997945]
 [0.44357971 0.74375896 0.27802475 0.03091768 0.2667871  0.55105675
  0.18026904 0.682537   0.53505813 0.51845121]
 [0.02949929 0.09703889 0.92134806 0.23757338 0.45947191 0.83352805
  0.33879694 0.35451551 0.08401488 0.03535116]
 [0.98547505 0.31036999 0.35913153 0.28304805 0.24498656 0.226378
  0.10564702 0.7348666  0.55737262 0.20769547]
 [0.38308066 0.13570696 0.49609954 0.78563739 0.3305499  0.26656969
  0.44962776 0.54824853 0.89676398 0.46353719]]

Subtract the mean of each row of the said matrix:

[[-8.74790185e-02  1.44568305e-01  5.21550713e-02  4.59301821e-01
  -3.70660410e-01  8.89444374e-02  2.76182297e-02 -3.75554093e-01
  -3.18063940e-01  3.79169598e-01]
 [ 2.05356766e-02  3.20714925e-01 -1.45019286e-01 -3.92126352e-01
  -1.56256930e-01  1.28012719e-01 -2.42774991e-01  2.59492964e-01
   1.12014094e-01  9.54071807e-02]
 [-3.09614522e-01 -2.4

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [13]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 4. 5. 1. 1. 4. 5. 2. 3. 2.]


# 12.How to get the diagonal of a dot product?

In [21]:
A = np.random.randint(0,10,(4,4))
B= np.random.randint(0,10,(4,4))

print(A)
print(B)
np.diag(np.dot(A, B))



[[1 2 0 9]
 [6 4 4 5]
 [1 7 8 1]
 [2 6 9 5]]
[[3 3 2 8]
 [9 2 8 2]
 [0 2 3 8]
 [6 6 7 7]]


array([ 75,  64,  89, 135])

# 13.How to find the most frequent value in an array?

In [26]:
A = np.random.randint(0,10,45)
print (A)
print('Rank:', np.bincount(A).argmax())

[8 0 3 0 6 5 5 9 0 2 2 7 3 8 6 2 5 7 8 0 0 7 6 1 7 1 5 1 2 7 5 2 0 8 5 9 8
 3 3 4 7 8 4 0 4]
Rank: 0


# 14.How to get the n largest values of an array

In [27]:
A = np.arange(20000)
np.random.shuffle(A)
n = 5

print (A[np.argsort(A)[-n:]])

[19995 19996 19997 19998 19999]


# 15.How to create a record array from a regular array?

In [31]:
A = np.array([("LOVE1", 2.5, 3),
              ("PYTHON", 3.6, 2)])
B = np.core.records.fromarrays(A.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

print(B)


[(b'LOVE1', 2.5, 3) (b'PYTHON', 3.6, 2)]
